<?php
require __DIR__ . '/../backend/ordenes_servicio/common.php';
$saleOrderId = filter_input(INPUT_GET, 'orden_venta_id', FILTER_VALIDATE_INT);
$serviceOrderId = filter_input(INPUT_GET, 'id', FILTER_VALIDATE_INT);
$prefijoRuta = '../';
require __DIR__ . '/../construct/header.php';
?>
<div class="container mt-5 mb-5 contain shadow-lg empresa-form-page"
     data-ov-csrf="<?= ov_escape($_SESSION['ordenes_venta_csrf']) ?>"
     data-sale-order-id="<?= ov_escape($saleOrderId ?: '') ?>"
     data-service-order-id="<?= ov_escape($serviceOrderId ?: '') ?>">
    <div class="row align-items-center pt-3 pb-4 mb-4 empresa-detalle-header">
        <div class="col"><p class="empresa-header-kicker mb-1">Operación</p><h1 id="os-form-title" class="h2 mb-1"><?= $serviceOrderId ? 'Editar orden de servicio' : 'Nueva orden de servicio' ?></h1><p class="empresa-header-subtitle mb-0">Configura los datos de ejecución, entrega y equipos del servicio.</p></div>
        <div class="col-12 col-md-auto mt-3 mt-md-0"><a id="os-back-top" href="ordenes_servicio.php" class="btn btn-secondary"><i class="bi bi-arrow-left" aria-hidden="true"></i> Volver</a></div>
    </div>
    <div id="mensaje_form_servicio" class="alert alert-info" role="status" aria-live="polite">Preparando el formulario...</div>
    <form id="form_orden_servicio" data-local-draft="1" class="d-none" novalidate>
        <input type="hidden" id="os-version">
        <section class="card mb-4 empresa-form-card"><div class="card-body empresa-card-body p-4">
            <div class="mb-4"><p class="empresa-section-kicker mb-1">Orden de venta de origen</p><h2 id="os-sale-number" class="h4 mb-1">—</h2><p id="os-company" class="op-company-title mb-0">—</p></div>
            <div class="row g-3"><div class="col-md-6 empresa-data-field"><div class="empresa-data-label">Oportunidad</div><div id="os-opportunity" class="empresa-data-value">—</div></div><div class="col-md-6 empresa-data-field"><div class="empresa-data-label">Cotización</div><div id="os-quote" class="empresa-data-value">—</div></div><div class="col-12 empresa-data-field"><div class="empresa-data-label">Descripción breve</div><div id="os-short-description" class="empresa-data-value ov-multiline">—</div></div><div class="col-12 empresa-data-field"><div class="empresa-data-label">Descripción larga</div><div id="os-long-description" class="empresa-data-value ov-multiline">—</div></div></div>
        </div></section>
        <section class="card mb-4 empresa-form-card"><div class="card-body empresa-card-body p-4">
            <div class="mb-4"><p class="empresa-section-kicker mb-1">Configuración</p><h2 class="h4 mb-1">Datos de la orden de servicio</h2></div>
            <div class="row g-3"><div class="col-md-4"><label class="form-label" for="os-date">Fecha de generación <span class="required-mark">*</span></label><input class="form-control" type="date" id="os-date" required></div><div class="col-md-4"><label class="form-label" for="os-type">Tipo de servicio <span class="required-mark">*</span></label><select class="form-select" id="os-type" required><option value="">Selecciona un tipo</option><?php foreach (OS_TIPOS as $key => $label): ?><option value="<?= ov_escape($key) ?>"><?= ov_escape($label) ?></option><?php endforeach; ?></select></div><div class="col-md-4"><label class="form-label" for="os-status">Estatus</label><select class="form-select" id="os-status"><?php foreach (OS_ESTATUS as $key => $label): ?><option value="<?= ov_escape($key) ?>"><?= ov_escape($label) ?></option><?php endforeach; ?></select></div></div>
        </div></section>
        <section class="card mb-4 empresa-form-card"><div class="card-body empresa-card-body p-4">
            <div class="mb-4"><p class="empresa-section-kicker mb-1">Cliente</p><h2 class="h4 mb-1">Datos fiscales y datos de entrega</h2></div>
            <div class="row g-4"><div class="col-lg-6 os-client-column"><h3 class="h5 mb-3">Datos fiscales</h3><div class="row g-3"><div class="col-12 empresa-data-field"><div class="empresa-data-label">Razón social</div><div id="os-fiscal-name" class="empresa-data-value">—</div></div><div class="col-md-5 empresa-data-field"><div class="empresa-data-label">RFC</div><div id="os-fiscal-rfc" class="empresa-data-value">—</div></div><div class="col-md-7 empresa-data-field"><div class="empresa-data-label">Régimen fiscal</div><div id="os-fiscal-regime" class="empresa-data-value">—</div></div><div class="col-12 empresa-data-field"><div class="empresa-data-label">Dirección fiscal</div><div id="os-fiscal-address" class="empresa-data-value ov-multiline">—</div></div></div></div><div class="col-lg-6 os-client-column"><h3 class="h5 mb-3">Entrega y atención del servicio</h3><div class="row g-3"><div class="col-12"><label class="form-label" for="os-delivery-address-select">Dirección de entrega o ejecución <span class="required-mark">*</span></label><select class="form-select" id="os-delivery-address-select" required><option value="">Selecciona una dirección</option></select><div id="os-delivery-address-detail" class="empresa-notes-help ov-multiline mt-2"></div></div><div class="col-12"><label class="form-label" for="os-delivery-contact-select">Contacto de entrega <span class="required-mark">*</span></label><select class="form-select" id="os-delivery-contact-select" required disabled><option value="">Selecciona primero una dirección</option></select></div><div class="col-md-6 empresa-data-field"><div class="empresa-data-label">Teléfono</div><div id="os-delivery-phone" class="empresa-data-value">—</div></div><div class="col-md-6 empresa-data-field"><div class="empresa-data-label">Correo electrónico</div><div id="os-delivery-email" class="empresa-data-value">—</div></div><div class="col-12 empresa-data-field"><div class="empresa-data-label">Puesto / departamento</div><div id="os-delivery-role" class="empresa-data-value">—</div></div></div></div></div>
        </div></section>
        <section class="card mb-4 empresa-form-card"><div class="card-body empresa-card-body p-4"><div class="mb-4"><p class="empresa-section-kicker mb-1">Ejecución</p><h2 class="h4 mb-1">Instrucciones y notas</h2></div><div class="row g-3"><div class="col-12"><label class="form-label" for="os-instructions">Instrucciones para ejecutar el servicio</label><textarea class="form-control" id="os-instructions" rows="4" maxlength="60000"></textarea></div><div class="col-12"><label class="form-label" for="os-notes">Notas internas</label><textarea class="form-control" id="os-notes" rows="3" maxlength="60000"></textarea></div></div></div></section>
        <section class="card mb-4 empresa-form-card"><div class="card-body empresa-card-body p-4"><div class="mb-4"><p class="empresa-section-kicker mb-1">Equipos</p><h2 class="h4 mb-1">Equipos incluidos en el servicio</h2><p class="empresa-notes-help mb-0">Selecciona un equipo registrado para la empresa y agrégalo a la orden.</p></div><div class="row g-2 align-items-end mb-4"><div class="col-md-9"><label class="form-label" for="os-equipment-select">Equipo de la empresa</label><select class="form-select" id="os-equipment-select"><option value="">Selecciona un equipo</option></select></div><div class="col-md-3"><button class="btn btn-secondary w-100" id="os-add-equipment" type="button"><i class="bi bi-plus-lg" aria-hidden="true"></i> Añadir equipo</button></div></div><div class="table-responsive data-table-shell table-wide"><table id="os-equipment-table" class="table table-striped align-middle mb-0"><thead><tr><th>Descripción de equipo</th><th>Ubicación</th><th>Marca</th><th>Modelo</th><th>Identificación</th><th>Serie</th><th>Capacidad</th><th>División real</th><th>División de verificación</th><th>Clase de exactitud</th><th>Acción</th><th>Estatus</th></tr></thead><tbody id="os-equipment-body"></tbody></table></div><div id="os-equipment-empty" class="alert alert-info mt-3 mb-0">No se han agregado equipos a esta orden.</div></div></section>
        <div class="d-flex flex-column flex-sm-row justify-content-sm-end gap-2 pb-4"><a id="os-cancel" href="ordenes_servicio.php" class="btn btn-danger">Cancelar</a><button id="os-save" class="btn btn-success" type="submit">Guardar orden de servicio</button></div>
    </form>
</div>
<script src="../js/ordenes-servicio-common.js?v=20261009-1"></script>
<script src="../js/formOrdenServicio.js?v=20261004-3"></script>
<?php require __DIR__ . '/../construct/footer.html'; ?>
