<?php
require __DIR__ . '/../backend/ordenes_venta/common.php';
$prefijoRuta = '../';
require __DIR__ . '/../construct/header.php';
?>
<div class="container mt-5 mb-5 contain shadow-lg empresa-detalle" data-ov-csrf="<?= ov_escape($_SESSION['ordenes_venta_csrf']) ?>">
    <div class="row align-items-center pt-3 pb-4 mb-4 empresa-detalle-header">
        <div class="col empresa-header-copy"><p class="empresa-header-kicker mb-1">Gestión comercial</p><h1 class="h2 mb-1 d-flex flex-wrap align-items-baseline gap-2"><span>Orden de venta</span><span id="ov-number" class="ov-title-number"></span><span id="ov-status" class="badge ov-status ov-title-status d-none"></span></h1><p class="empresa-header-subtitle mb-0">Origen comercial y órdenes operativas derivadas</p></div>
        <div class="col-12 col-md-auto mt-3 mt-md-0 d-flex flex-column flex-sm-row gap-2 empresa-header-actions"><button id="ov-copy" class="btn btn-success d-none" type="button"><i class="bi bi-clipboard" aria-hidden="true"></i> Copiar información</button><a id="ov-edit" class="btn btn-secondary d-none"><i class="bi bi-pencil" aria-hidden="true"></i> Editar orden</a><a href="ordenes_venta.php" class="btn btn-secondary"><i class="bi bi-arrow-left" aria-hidden="true"></i> Órdenes de venta</a></div>
    </div>
    <div id="mensaje_orden" class="alert d-none mt-4" role="status" aria-live="polite"></div>
    <div id="ov-detail" class="d-none">
        <section class="card mb-4 empresa-form-card empresa-detail-section"><div class="card-body empresa-card-body"><div class="empresa-section-heading mb-3"><p class="empresa-section-kicker mb-1">Números de control</p><h2 class="h5 card-title mb-0">Origen y compromiso comercial</h2></div><div class="row g-3"><div class="col-md-3 empresa-data-field"><div class="empresa-data-label">Oportunidad de venta</div><a id="ov-opportunity" class="empresa-data-value entity-link"></a></div><div class="col-md-3 empresa-data-field"><div class="empresa-data-label">Cotización</div><a id="ov-quote" class="empresa-data-value entity-link"></a></div><div class="col-md-3 empresa-data-field"><div class="empresa-data-label">Fecha de generación</div><div id="ov-date" class="empresa-data-value"></div></div><div class="col-md-3 empresa-data-field"><div class="empresa-data-label">Fecha compromiso</div><div id="ov-scheduled" class="empresa-data-value"></div></div></div></div></section>
        <section class="card mb-4 empresa-form-card empresa-detail-section"><div class="card-body empresa-card-body"><div class="empresa-section-heading mb-3"><p class="empresa-section-kicker mb-1">Cliente de la orden</p><a id="ov-company" class="op-company-title entity-link"></a></div><div class="row g-3 mt-1"><div class="col-12 empresa-data-field"><div class="empresa-data-label">Dirección</div><div id="ov-address" class="empresa-data-value ov-multiline"></div></div><div class="col-md-4 empresa-data-field"><div class="empresa-data-label">Contacto</div><a id="ov-contact" class="empresa-data-value entity-link"></a></div><div class="col-md-4 empresa-data-field"><div class="empresa-data-label">Teléfono</div><div id="ov-phone" class="empresa-data-value"></div></div><div class="col-md-4 empresa-data-field"><div class="empresa-data-label">Correo electrónico</div><div id="ov-email" class="empresa-data-value"></div></div></div></div></section>
        <section class="card mb-4 empresa-form-card empresa-detail-section"><div class="card-body empresa-card-body"><div class="empresa-section-heading mb-3"><p class="empresa-section-kicker mb-1">Proyecto</p><h2 class="h5 card-title mb-0">Descripciones de la orden de venta</h2></div><div class="row g-3"><div class="col-12 empresa-data-field"><div class="empresa-data-label">Descripción breve</div><div id="ov-short-description" class="empresa-data-value ov-multiline"></div></div><div class="col-12 empresa-data-field"><div class="empresa-data-label">Descripción larga</div><div id="ov-long-description" class="empresa-data-value ov-multiline"></div></div></div></div></section>
        <section class="card mb-4 empresa-form-card empresa-detail-section"><div class="card-body empresa-card-body"><div class="empresa-section-heading mb-3"><p class="empresa-section-kicker mb-1">Ejecución</p><h2 class="h5 card-title mb-0">Instrucciones y anotaciones</h2></div><div class="row g-3"><div class="col-12 empresa-data-field"><div class="empresa-data-label">Instrucciones para realizar el servicio o trabajo</div><div id="ov-instructions" class="empresa-data-value ov-multiline"></div></div><div class="col-12 empresa-data-field"><div class="empresa-data-label">Notas internas</div><div id="ov-notes" class="empresa-data-value ov-multiline"></div></div></div></div></section>
        <section class="card mb-4 empresa-form-card empresa-detail-section"><div class="card-body empresa-card-body"><div class="empresa-section-heading mb-3 d-flex flex-column flex-md-row justify-content-between align-items-md-center gap-3"><div><p class="empresa-section-kicker mb-1">Siguiente nivel</p><h2 class="h5 card-title mb-0">Órdenes operativas derivadas</h2></div><a id="ov-new-service" class="btn btn-success"><i class="bi bi-plus-lg" aria-hidden="true"></i> Nueva orden de servicio</a></div><div class="table-responsive data-table-shell"><table id="ov-service-table" class="table table-striped align-middle mb-0"><thead><tr><th>Orden de servicio</th><th>Fecha</th><th>Tipo</th><th>Estatus</th><th>Última actualización</th></tr></thead><tbody id="ov-service-orders"></tbody></table></div><div id="ov-service-empty" class="alert alert-info mt-3 mb-0 d-none">Esta orden de venta todavía no tiene órdenes de servicio relacionadas.</div></div></section>
        <section class="card mb-4 empresa-form-card empresa-detail-section"><div class="card-body empresa-card-body"><div class="empresa-section-heading mb-3"><p class="empresa-section-kicker mb-1">Seguimiento</p><h2 class="h5 card-title mb-0">Control del registro</h2></div><div id="ov-audit" class="empresa-data-value mb-4"></div><div id="ov-followups" class="ov-followup-list"></div></div></section>
    </div>
</div>
<script src="../js/ordenes-venta-common.js?v=20261004-1"></script>
<script src="../js/verOrdenVenta.js?v=20261007-1"></script>
<?php require __DIR__ . '/../construct/footer.html'; ?>
