<?php
require __DIR__ . '/../backend/ordenes_servicio/common.php';
$prefijoRuta = '../';
require __DIR__ . '/../construct/header.php';
?>
<div class="container mt-5 mb-5 contain shadow-lg empresa-detalle" data-ov-csrf="<?= ov_escape($_SESSION['ordenes_venta_csrf']) ?>">
    <div class="row align-items-center pt-3 pb-4 mb-4 empresa-detalle-header"><div class="col"><p class="empresa-header-kicker mb-1">Operación</p><h1 class="h2 mb-1 d-flex flex-wrap align-items-baseline gap-2"><span>Orden de servicio</span><span id="os-number" class="ov-title-number"></span><span id="os-status" class="badge os-status ov-title-status d-none"></span></h1><p class="empresa-header-subtitle mb-0">Documento operativo y evidencia para firma del cliente</p></div><div class="col-12 col-lg-auto mt-3 mt-lg-0 d-flex flex-column flex-sm-row gap-2"><a id="os-print" class="btn btn-success d-none" target="_blank" rel="noopener"><i class="bi bi-printer" aria-hidden="true"></i> Imprimir orden</a><a id="os-edit" class="btn btn-secondary d-none"><i class="bi bi-pencil" aria-hidden="true"></i> Editar orden</a><a href="ordenes_servicio.php" class="btn btn-secondary"><i class="bi bi-arrow-left" aria-hidden="true"></i> Volver</a></div></div>
    <div id="mensaje_servicio" class="alert d-none mt-4" role="status" aria-live="polite"></div>
    <div id="os-detail" class="d-none">
        <section class="card mb-4 empresa-form-card"><div class="card-body empresa-card-body"><div class="empresa-section-heading mb-3"><p class="empresa-section-kicker mb-1">Control</p><h2 class="h5 mb-0">Datos de la orden</h2></div><div class="row g-3"><div class="col-md-3 empresa-data-field"><div class="empresa-data-label">Fecha de generación</div><div id="os-date" class="empresa-data-value"></div></div><div class="col-md-3 empresa-data-field"><div class="empresa-data-label">Tipo de servicio</div><div id="os-type" class="empresa-data-value"></div></div><div class="col-md-3 empresa-data-field"><div class="empresa-data-label">Orden de venta</div><a id="os-sale" class="empresa-data-value entity-link"></a></div><div class="col-md-3 empresa-data-field"><div class="empresa-data-label">Empresa</div><a id="os-company" class="empresa-data-value entity-link"></a></div></div></div></section>
        <section class="card mb-4 empresa-form-card"><div class="card-body empresa-card-body"><div class="empresa-section-heading mb-3"><p class="empresa-section-kicker mb-1">Cliente</p><h2 class="h5 mb-0">Datos fiscales y de entrega</h2></div><div class="row g-4"><div class="col-lg-6 os-client-column"><h3 class="h6">Datos fiscales</h3><div id="os-fiscal" class="ov-multiline empresa-data-value"></div></div><div class="col-lg-6 os-client-column"><h3 class="h6">Entrega y contacto</h3><div id="os-delivery" class="ov-multiline empresa-data-value"></div></div></div></div></section>
        <section class="card mb-4 empresa-form-card"><div class="card-body empresa-card-body"><div class="empresa-section-heading mb-3"><p class="empresa-section-kicker mb-1">Ejecución</p><h2 class="h5 mb-0">Instrucciones y notas</h2></div><div class="row g-3"><div class="col-12 empresa-data-field"><div class="empresa-data-label">Instrucciones</div><div id="os-instructions" class="empresa-data-value ov-multiline"></div></div><div class="col-12 empresa-data-field"><div class="empresa-data-label">Notas internas</div><div id="os-notes" class="empresa-data-value ov-multiline"></div></div></div></div></section>
        <section class="card mb-4 empresa-form-card"><div class="card-body empresa-card-body"><div class="empresa-section-heading mb-3"><p class="empresa-section-kicker mb-1">Equipos</p><h2 class="h5 mb-0">Equipos incluidos en el servicio</h2></div><div class="table-responsive data-table-shell table-wide"><table id="os-detail-equipment" class="table table-striped align-middle mb-0"><thead><tr><th>Descripción de equipo</th><th>Ubicación</th><th>Marca</th><th>Modelo</th><th>Identificación</th><th>Serie</th><th>Capacidad</th><th>División real</th><th>División de verificación</th><th>Clase de exactitud</th></tr></thead><tbody id="os-detail-equipment-body"></tbody></table></div><div id="os-detail-equipment-empty" class="alert alert-info mt-3 mb-0 d-none">Esta orden no tiene equipos registrados.</div></div></section>
    </div>
</div>
<script src="../js/ordenes-servicio-common.js?v=20261004-1"></script><script src="../js/verOrdenServicio.js?v=20261004-3"></script>
<?php require __DIR__ . '/../construct/footer.html'; ?>
